### ISSUE TITLE
提币不到账卡着怎么回事啊？

### ISSUE THREAD

**Issue by BEJMGTZ1** [bluehelix-chain/Custom-issues#1]
提heco链卡着不到账怎么回事啊

订单ID
d2074add-7502-4a1e-a556-1df1445c6b3f

内链哈希
631EDE23DA8764EE698966BA510EC446B57B3BCE2BA036724FFE6B145C76B50F

**Comment by keeper586** [comment]
https://explorer.bhexchain.com/orders/d2074add-7502-4a1e-a556-1df1445c6b3f
该笔提币已经完成。

**Comment by BEJMGTZ1** [comment]
Thanks

**Comment by BEJMGTZ1** [comment]
> https://explorer.bhexchain.com/orders/d2074add-7502-4a1e-a556-1df1445c6b3f
> 该笔提币已经完成。

Thanks

**Comment by BEJMGTZ1** [comment]
> https://explorer.bhexchain.com/orders/d2074add-7502-4a1e-a556-1df1445c6b3f 该笔提币已经完成。

订单ID
e97e774e-aa01-4dfb-9a6f-97be3c323e86

内链哈希：935AA919C4AC0BD41C8798B6C5D463BEB90F6E2CF4375992F2E22A8481AE2A2A

eth链有额度，怎么回事呢？

**Comment by keeper586** [comment]
The eth chainnode stopped  because of  go eth's "Head state missing, repairing" problem. Now we are trying to fix it.

**Comment by BEJMGTZ1** [comment]
多久可以修复啊，还有不到两天火币就关闭充值了。

另外，这笔可以取消吗，不提了，原路退回来啊？

**Comment by BEJMGTZ1** [comment]
> The eth chainnode stopped because of go eth's "Head state missing, repairing" problem. Now we are trying to fix it.

一直提示哈希不匹配，可以取消吗，现在卡着也是这么回事啊，再过两天火币关闭充值了，到时候就麻烦了啊

**Comment by BEJMGTZ1** [comment]
> The eth chainnode stopped because of go eth's "Head state missing, repairing" problem. Now we are trying to fix it.

这个提币能不能取消啊，扣点费用也行啊
